"""
Shanghai ANTL-GDP Regression Analysis (2013-2022)
Analyzes relationship between Average Nighttime Light (ANTL) and GDP
using multiple regression models to select the best-fitting model.

Data embedded directly to avoid cross-thread file access issues.
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.preprocessing import StandardScaler
import json
from storage_manager import storage_manager

# Output paths
output_csv_path = storage_manager.resolve_output_path('shanghai_antl_gdp_regression_results.csv')
output_plot_path = storage_manager.resolve_output_path('shanghai_antl_gdp_regression_plot.png')
output_report_path = storage_manager.resolve_output_path('shanghai_antl_gdp_model_comparison.json')

# Embed ANTL data from NTL_raster_statistics output (2013-2022)
# Source: shanghai_antl_2013_2022.csv generated by NTL_raster_statistics
antl_data = {
    'year': [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    'ANTL': [12.6935, 12.3080, 12.6828, 12.6039, 13.9421, 13.6770, 14.2958, 14.4234, 14.9202, 14.8432]
}
antl_df = pd.DataFrame(antl_data)
print("ANTL Data (from NTL_raster_statistics):")
print(antl_df)

# Embed GDP data from China_Official_GDP_tool output (2013-2022)
# Source: shanghai_gdp_2013_2022.csv, unit: 100 million CNY
gdp_data = {
    'year': [2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
    'GDP': [23809.4, 25964.5, 27821.6, 30963.9, 34378.3, 37769.1, 40241.2, 41603.9, 47059.4, 48594.5]
}
gdp_df = pd.DataFrame(gdp_data)
print("\nGDP Data (from NBS Official API):")
print(gdp_df)

# Merge datasets
data = pd.merge(antl_df, gdp_df, on='year')
print("\nMerged Data:")
print(data)

# Prepare features and target
X = data[['ANTL']].values
y = data['GDP'].values
years = data['year'].values

print(f"\nData shape: {len(data)} samples")
print(f"ANTL range: {X.min():.2f} - {X.max():.2f}")
print(f"GDP range: {y.min():.2f} - {y.max():.2f}")

# Scale features for regularization models
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Define models
models = {
    'OLS': LinearRegression(),
    'Ridge (α=1.0)': Ridge(alpha=1.0),
    'Ridge (α=10.0)': Ridge(alpha=10.0),
    'Lasso (α=0.1)': Lasso(alpha=0.1),
    'Lasso (α=1.0)': Lasso(alpha=1.0),
    'ElasticNet (α=1.0)': ElasticNet(alpha=1.0, l1_ratio=0.5),
    'RandomForest (n=100)': RandomForestRegressor(n_estimators=100, random_state=42),
    'RandomForest (n=500)': RandomForestRegressor(n_estimators=500, random_state=42),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=100, random_state=42),
    'SVR (RBF)': SVR(kernel='rbf', C=100, gamma=0.1)
}

# Train and evaluate models
results = []
for name, model in models.items():
    # Use scaled data for regularized models, raw for others
    if 'Ridge' in name or 'Lasso' in name or 'ElasticNet' in name or 'SVR' in name:
        X_train = X_scaled
    else:
        X_train = X
    
    model.fit(X_train, y)
    y_pred = model.predict(X_train)
    
    r2 = r2_score(y, y_pred)
    rmse = np.sqrt(mean_squared_error(y, y_pred))
    mae = mean_absolute_error(y, y_pred)
    
    results.append({
        'Model': name,
        'R2': r2,
        'RMSE': rmse,
        'MAE': mae
    })
    print(f"\n{name}:")
    print(f"  R² = {r2:.6f}")
    print(f"  RMSE = {rmse:.2f}")
    print(f"  MAE = {mae:.2f}")

# Create results DataFrame
results_df = pd.DataFrame(results)
print("\n" + "="*60)
print("MODEL COMPARISON SUMMARY")
print("="*60)
print(results_df.to_string(index=False))

# Sort by R² (descending) to find best model
results_df_sorted = results_df.sort_values('R2', ascending=False)
best_model = results_df_sorted.iloc[0]['Model']
best_r2 = results_df_sorted.iloc[0]['R2']
print(f"\nBest Model: {best_model} (R² = {best_r2:.6f})")

# For practical purposes, exclude overfitted models (R² > 0.999 on training)
# and select best non-overfitted model
non_overfit_results = results_df[results_df['R2'] < 0.999]
if len(non_overfit_results) > 0:
    non_overfit_sorted = non_overfit_results.sort_values('R2', ascending=False)
    best_practical_model = non_overfit_sorted.iloc[0]['Model']
    best_practical_r2 = non_overfit_sorted.iloc[0]['R2']
    print(f"\nBest Practical Model (non-overfitted): {best_practical_model} (R² = {best_practical_r2:.6f})")
else:
    best_practical_model = best_model
    best_practical_r2 = best_r2

# Save results to CSV
results_df.to_csv(output_csv_path, index=False)
print(f"\nResults saved to: {output_csv_path}")

# Create visualization
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1: ANTL vs GDP scatter with OLS fit (most interpretable)
ax1 = axes[0, 0]
ax1.scatter(X.flatten(), y, c='blue', s=100, alpha=0.7, label='Observed')
ax1.set_xlabel('ANTL (Average Nighttime Light)', fontsize=12)
ax1.set_ylabel('GDP (100 million CNY)', fontsize=12)
ax1.set_title(f'Shanghai ANTL vs GDP (2013-2022)\nCorrelation: {data["ANTL"].corr(data["GDP"]):.4f}', fontsize=14)

# Plot OLS line for interpretation
ols_model = LinearRegression()
ols_model.fit(X, y)
X_line = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)
y_line = ols_model.predict(X_line)
ax1.plot(X_line, y_line, 'r-', linewidth=2, label=f'OLS Fit (R²={r2_score(y, ols_model.predict(X)):.4f})')
ax1.legend(fontsize=10)
ax1.grid(True, alpha=0.3)

# Annotate years (using scalar values)
for i, year in enumerate(years):
    ax1.annotate(str(int(year)), (float(X[i, 0]), float(y[i])), xytext=(5, 5), textcoords='offset points', fontsize=9)

# Plot 2: Model comparison (R²)
ax2 = axes[0, 1]
colors = plt.cm.viridis(np.linspace(0, 1, len(results_df)))
bars = ax2.barh(results_df['Model'], results_df['R2'], color=colors)
ax2.set_xlabel('R² Score', fontsize=12)
ax2.set_title('Model Comparison by R²', fontsize=14)
ax2.grid(True, alpha=0.3, axis='x')
ax2.tick_params(axis='x', labelrotation=0)

# Highlight best practical model
best_practical_idx = results_df[results_df['Model'] == best_practical_model].index[0]
bars[best_practical_idx].set_color('red')
bars[best_practical_idx].set_edgecolor('black')
bars[best_practical_idx].set_linewidth(2)

# Plot 3: RMSE comparison
ax3 = axes[1, 0]
bars3 = ax3.barh(results_df['Model'], results_df['RMSE'], color=colors)
ax3.set_xlabel('RMSE (100 million CNY)', fontsize=12)
ax3.set_title('Model Comparison by RMSE', fontsize=14)
ax3.grid(True, alpha=0.3, axis='x')
bars3[best_practical_idx].set_color('red')
bars3[best_practical_idx].set_edgecolor('black')
bars3[best_practical_idx].set_linewidth(2)

# Plot 4: Predicted vs Actual (using OLS for interpretability)
ax4 = axes[1, 1]
y_pred_ols = ols_model.predict(X)
ax4.scatter(y, y_pred_ols, c='green', s=100, alpha=0.7)
ax4.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', linewidth=2, label='Perfect Fit')
ax4.set_xlabel('Actual GDP (100 million CNY)', fontsize=12)
ax4.set_ylabel('Predicted GDP (100 million CNY)', fontsize=12)
ax4.set_title(f'Predicted vs Actual (OLS Model)', fontsize=14)
ax4.legend(fontsize=10)
ax4.grid(True, alpha=0.3)

# Add R² and RMSE text
ols_r2 = r2_score(y, y_pred_ols)
ols_rmse = np.sqrt(mean_squared_error(y, y_pred_ols))
ax4.text(0.05, 0.95, f'R² = {ols_r2:.4f}\nRMSE = {ols_rmse:.2f}',
         transform=ax4.transAxes, fontsize=12, verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

plt.tight_layout()
plt.savefig(output_plot_path, dpi=150, bbox_inches='tight')
print(f"Visualization saved to: {output_plot_path}")
plt.close()

# Save detailed report as JSON
report = {
    'analysis_info': {
        'study_area': 'Shanghai',
        'time_range': '2013-2022',
        'data_points': int(len(data)),
        'feature': 'ANTL (Average Nighttime Light)',
        'target': 'GDP (100 million CNY)'
    },
    'best_model': {
        'name': str(best_practical_model),
        'r2': float(best_practical_r2),
        'rmse': float(results_df[results_df['Model'] == best_practical_model]['RMSE'].values[0]),
        'mae': float(results_df[results_df['Model'] == best_practical_model]['MAE'].values[0])
    },
    'best_raw_model': {
        'name': str(best_model),
        'r2': float(best_r2),
        'note': 'May be overfitted (R² > 0.999)'
    },
    'all_models': results_df.to_dict('records'),
    'data_summary': {
        'antl_mean': float(data['ANTL'].mean()),
        'antl_std': float(data['ANTL'].std()),
        'gdp_mean': float(data['GDP'].mean()),
        'gdp_std': float(data['GDP'].std()),
        'correlation': float(data['ANTL'].corr(data['GDP']))
    }
}

with open(output_report_path, 'w') as f:
    json.dump(report, f, indent=2)
print(f"Detailed report saved to: {output_report_path}")

print("\n" + "="*60)
print("ANALYSIS COMPLETE")
print("="*60)
print(f"Best Practical Model: {best_practical_model}")
print(f"R² Score: {best_practical_r2:.6f}")
print(f"RMSE: {results_df[results_df['Model'] == best_practical_model]['RMSE'].values[0]:.2f}")
print(f"MAE: {results_df[results_df['Model'] == best_practical_model]['MAE'].values[0]:.2f}")
print(f"Correlation (ANTL-GDP): {data['ANTL'].corr(data['GDP']):.4f}")