"""
Script to identify the district in Shanghai with the highest ANTL in 2022 NPP-VIIRS-like image.
"""
from storage_manager import storage_manager
import pandas as pd

# The statistics CSV was generated by NTL_raster_statistics tool, so it's in outputs
csv_path = storage_manager.resolve_output_path('shanghai_district_antl_2022.csv')

# Read the district ANTL statistics
df = pd.read_csv(csv_path)

# Display column names to understand the structure
print("CSV Columns:", df.columns.tolist())
print("\nFirst few rows:")
print(df.head())

# Find the district with the highest ANTL
# Assuming the CSV has columns like 'Name' (district name) and 'ANTL'
if 'ANTL' in df.columns:
    # Find the row with maximum ANTL
    max_antl_row = df.loc[df['ANTL'].idxmax()]
    
    # Get the district name - could be 'Name' or similar
    name_col = None
    for col in ['Name', 'name', 'district', 'district_name', 'NAME']:
        if col in df.columns:
            name_col = col
            break
    
    if name_col:
        district_name = max_antl_row[name_col]
        max_antl_value = max_antl_row['ANTL']
        
        print(f"\n{'='*60}")
        print(f"RESULT: District with Highest ANTL in Shanghai (2022)")
        print(f"{'='*60}")
        print(f"District Name: {district_name}")
        print(f"ANTL Value: {max_antl_value:.4f}")
        print(f"{'='*60}")
        
        # Save result to output CSV
        result_df = pd.DataFrame({
            'district_name': [district_name],
            'ANTL': [max_antl_value],
            'year': [2022],
            'rank': [1]
        })
        
        output_path = storage_manager.resolve_output_path('shanghai_highest_antl_district_2022.csv')
        result_df.to_csv(output_path, index=False)
        print(f"\nResult saved to: {output_path}")
        
        # Also print all districts sorted by ANTL for reference
        print("\nAll districts sorted by ANTL (descending):")
        sorted_df = df.sort_values('ANTL', ascending=False)
        if name_col:
            print(sorted_df[[name_col, 'ANTL']].to_string(index=False))
    else:
        print("Error: Could not find district name column in CSV")
        print("Available columns:", df.columns.tolist())
else:
    print("Error: 'ANTL' column not found in CSV")
    print("Available columns:", df.columns.tolist())
