TEST_CASES = [
    # ---------- Data retrieval and preprocessing ----------
    {"cat": "Data retrieval and preprocessing", "label": "NPP VIIRS Annual",
     "query": "Retrieve NPP VIIRS Annual NTL data for Shanghai from 2020–2022."},
    {"cat": "Data retrieval and preprocessing", "label": "DMSP–OLS Annual < 2013",
     "query": "Retrieve DMSP–OLS Annual NTL data for Shanghai from 2005 to 2010."},
    {"cat": "Data retrieval and preprocessing", "label": "NPP-VIIRS-like Annual 2000–2023",
     "query": "Retrieve NPP-VIIRS-like Annual NTL data for Shanghai from 2010 to 2020."},
    {"cat": "Data retrieval and preprocessing", "label": "NPP VIIRS Monthly 2020",
     "query": "Retrieve NPP VIIRS Monthly NTL data for Shanghai from January to December 2020."},
    {"cat": "Data retrieval and preprocessing", "label": "VNP46A1 Daily 2020-12-01~07",
     "query": "Retrieve NPP VIIRS VNP46A1 Daily NTL data for Shanghai from December 1 to December 7, 2020."},
    {"cat": "Data retrieval and preprocessing", "label": "VNP46A2 Daily Jan-2020 + monthly composite",
     "query": "Retrieve NPP VIIRS VNP46A2 Daily NTL data for Shanghai, from January 1 to January 31, 2020，and composite them into a monthly NTL imagery"},
    {"cat": "Data retrieval and preprocessing", "label": "VNP46A2 zenith-angle correction",
     "query": "Perform zenith angle correction on daily VNP46A2 NTL data for Shanghai from Jan 1 to Dec 31, 2024."},
    {"cat": "Data retrieval and preprocessing", "label": "SDGSAT-1 Preprocessing",
     "query": "Perform stripe noise removal and radiometric calibration on SDGSAT-1 GLI image at \"./NTL_Agent/Night_data/SDGSAT-1/Test1_radiance_rgb.tif\""},
    {"cat": "Data retrieval and preprocessing", "label": "SDGSAT-1 Grayscale brightness",
     "query": "Create grayscale brightness image using SDGSAT-1 GLI image at \"./NTL_Agent/Night_data/SDGSAT-1/Test1_radiance_rgb.tif\""},
    {"cat": "Data retrieval and preprocessing", "label": "SDGSAT-1 NDIGR",
     "query": "Caculate NDIGR using SDGSAT-1 GLI image at \"./NTL_Agent/Night_data/SDGSAT-1/Test1_radiance_rgb.tif\""},

    # ---------- NTL statistical and spatial analysis ----------
    {"cat": "NTL statistical and spatial analysis", "label": "Numerical Statistics: MaxNTL, MinNTL, SDNTL, HistNTL, TNTL, LArea, 3DPL, ANTL, DNTL",
     "query": "Caculate Maximum NTL intensity of NPP-VIIRS-like Annual NTL image for Shanghai in 2020. Maximum NTL intensity [MaxNTL(P)], Minimum NTL intensity [MinNTL], Standard deviation of NTL [SDNTL], Pixel value distribution [HistNTL], Total NTL intensity [TNTL], Total lit area [LArea], 3D percentage of landscape area [3DPL], 3D edge density [3DED], 3D largest patch index [3DLPI], Average NTL intensity [ANTL], Deviation of NTL intensity [DNTL]"},
    {"cat": "NTL statistical and spatial analysis", "label": "Highest ANTL district",
     "query": "Identify the district in Shanghai with the highest Average NTL intensity in the 2020 NPP-VIIRS-like image."},
    {"cat": "NTL statistical and spatial analysis", "label": "Brightest pixel coord",
     "query": "Identify the coordinate of the brightest pixel of NPP-VIIRS NTL imagery in Shanghai, 2022."},
    {"cat": "NTL statistical and spatial analysis", "label": "NTL at Oriental Pearl Tower",
     "query": "Report the NTL intensity of NPP-VIIRS imagery at the location of the Oriental Pearl Tower in 2020."},
    {"cat": "NTL statistical and spatial analysis", "label": "Threshold statistics",
     "query": "Within the administrative boundary of Shanghai in 2020, calculate the total area and proportion of NPP-VIIRS nighttime light pixels with values greater than 50."},
    {"cat": "NTL statistical and spatial analysis", "label": "Total NTL growth rate",
     "query": "Calculate the growth rate of Total NTL intensity for Shanghai from 2015 to 2020."},
    {"cat": "NTL statistical and spatial analysis", "label": "District growth rate",
     "query": "Calculate the NTL growth rate for each district of Shanghai from 2019 to 2020."},
    {"cat": "NTL statistical and spatial analysis", "label": "District with highest growth",
     "query": "Identify the district with the highest NTL growth rate in Shanghai from 2019 to 2020."},
    {"cat": "NTL statistical and spatial analysis", "label": "Anomaly detection",
     "query": "Detect anomalous pixels in Shanghai from 2015 to 2020."},
    {"cat": "NTL statistical and spatial analysis", "label": "VNP46A2 ANTL in GEE",
     "query": "Caculate VNP46A2 Average NTL intensity in Shanghai, from January 1, 2022, to January 31, 2022, using GEE Python Code，and save it as a csv to my Driver."},
    {"cat": "NTL statistical and spatial analysis", "label": "Diff map",
     "query": "Calculate and visualize the NTL brightness difference between 2020 and 2021 in Shanghai."},
    {"cat": "NTL statistical and spatial analysis", "label": "Compare ANTL Shanghai vs Beijing",
     "query": "Compare Average NTL intensity in Shanghai and Beijing in 2022 and tell me which is brighter."},

    # ---------- NTL application and modeling ----------
    {"cat": "NTL application and modeling", "label": "Myanmar earthquake",
     "query": "Analyze the impact of the 2025 Myanmar earthquake using daily NTL imagery and multi-source news content. Retrieve authoritative event details and identify the most affected regions and quantify changes in nighttime brightness before and after the event to infer damage levels."},
    {"cat": "NTL application and modeling", "label": "DEI & ANTL",
     "query": "Please read the 2022 DEI data for the top 20 Chinese cities from .\\NTL_Agent\\DEI\\DEI_1_20.xlsx, retrieve the corresponding 2022 ANTL (annual average nighttime light) values for these cities, analyze the relationship between ANTL and DEI, and fit a regression model for analysis."},
    {"cat": "NTL application and modeling", "label": "GDP & ANTL",
     "query": "Please read Shanghai’s GDP data from .\\NTL_Agent\\GDP\\Shanghai.xlsx, retrieve the NPP VIIRS nighttime light imagery for the years 2013–2022, and compute the annual average nighttime light (ANTL) for each year. Then, analyze the relationship between ANTL and GDP, and test multiple regression models to identify and select the best-fitting model for GDP estimation using ANTL."},
    {"cat": "NTL application and modeling", "label": "Built-up area ratio per district",
     "query": "Download the 2020 NTL imagery for Shanghai. Then, extract the built-up area using a change-point detection method. Finally, calculate the proportion of built-up area within each administrative district of Shanghai."},
    {"cat": "NTL application and modeling", "label": "Main roads from SDGSAT-1 GLI",
     "query": "Extract urban main roads based on the SDGSAT-1 GLI NTL imagery located at .\\NTL_Agent\\Night_data\\SDGSAT-1\\SDG_rgb.tif."},
    {"cat": "NTL application and modeling", "label": "SDG 7.1.1 electricity access (VIIRS + LandScan)",
     "query": "Please use the 2020 NPP-VIIRS nighttime light imagery and LandScan population data to measure the population with access to electricity, in accordance with the methodology for SDG Indicator 7.1.1 (Proportion of population with access to electricity)."},
    {"cat": "NTL application and modeling", "label": "RRLI & RBLI + streetlight type (SDGSAT-1)",
     "query": "Compute the Ratio Red Light Index (RRLI) and Ratio Blue Light Index (RBLI) based on the SDGSAT-1 GLI NTL imagery located at .\\NTL-Claw\\Night_data\\SDGSAT-1\\SDG_rgb.tif. Then, classify the streetlight types."},
]

CATEGORIES = ["Data retrieval and preprocessing",
              "NTL statistical and spatial analysis",
              "NTL application and modeling"]
