"""
Template: Amap boundary + GEE annual NTL zonal statistics.

Purpose
- Use an Amap-derived administrative boundary shapefile in local workspace.
- Pull annual NPP-VIIRS-like NTL from Earth Engine.
- Compute district-level ANTL via reduceRegions.
- Export table CSV for downstream regression/modeling.

Expected inputs
- A boundary shapefile generated by get_administrative_division_data, e.g.:
  "shanghai_districts_boundary.shp"

Expected outputs
- A CSV in outputs/, e.g. "shanghai_districts_antl_2020.csv"
"""

from __future__ import annotations

import json
import os

import ee
import geopandas as gpd
import pandas as pd

from storage_manager import storage_manager


def compute_antl_zonal_stats(
    boundary_filename: str,
    out_csv_name: str,
    start_date: str = "2020-01-01",
    end_date: str = "2020-12-31",
    dataset_id: str = "projects/sat-io/open-datasets/npp-viirs-ntl",
    band: str = "b1",
    gee_project: str | None = None,
    scale: int = 500,
) -> str:
    """Run annual NTL zonal stats over an administrative boundary."""
    project_id = gee_project or os.getenv("GEE_PROJECT_ID") or "empyrean-caster-430308-m2"
    ee.Initialize(project=project_id)

    boundary_path = storage_manager.resolve_input_path(boundary_filename)
    gdf = gpd.read_file(boundary_path)
    if gdf.empty:
        raise ValueError(f"Boundary file is empty: {boundary_filename}")

    # Ensure WGS84 for robust EE ingestion.
    if gdf.crs and gdf.crs.to_epsg() != 4326:
        gdf = gdf.to_crs(epsg=4326)

    fc = ee.FeatureCollection(json.loads(gdf.to_json()))
    image = (
        ee.ImageCollection(dataset_id)
        .filterDate(start_date, end_date)
        .select(band)
        .first()
    )
    if image is None:
        raise RuntimeError("No image found for the requested date range.")

    stats_fc = image.reduceRegions(
        collection=fc,
        reducer=ee.Reducer.mean().setOutputs(["ANTL"]),
        scale=scale,
        maxPixelsPerRegion=1e13,
        tileScale=4,
    )

    rows = [f.get("properties", {}) for f in stats_fc.getInfo().get("features", [])]
    df = pd.DataFrame(rows)

    out_csv = storage_manager.resolve_output_path(out_csv_name)
    df.to_csv(out_csv, index=False)
    return out_csv


if __name__ == "__main__":
    out_file = compute_antl_zonal_stats(
        boundary_filename="shanghai_districts_boundary.shp",
        out_csv_name="shanghai_districts_antl_2020.csv",
        start_date="2020-01-01",
        end_date="2020-12-31",
    )
    print(f"Saved zonal stats CSV: {out_file}")
